apiVersion: v1
kind: Secret
metadata:
  name: {{ include "meet.fullname" . }}-secret
type: Opaque
data:
  db-password: {{ .Values.secrets.dbPassword | b64enc | quote }}
  db-redisauth: {{ .Values.secrets.dbredisauth | b64enc | quote }}